from __future__ import annotations


SALES_SCRIPTS = [
    {
        "category": "Door Knocking",
        "title": "First-Time Stop",
        "use_case": "Walking into a business for the first time.",
        "text": "Hey, how's it going? My name is [Name] with [Company]. We work with local businesses around here, and I'm stopping by a few places today. Is the owner or manager around for a quick second?",
    },
    {
        "category": "Door Knocking",
        "title": "Busy Employee / Manager Unavailable",
        "use_case": "Staff is busy or says the manager is not available.",
        "text": "No problem at all. What day or time is usually best to catch them? I can leave a card, but I'd rather stop by when it is actually convenient.",
    },
    {
        "category": "Door Knocking",
        "title": "Dirty Glass Observation",
        "use_case": "Using a visible storefront issue as the reason for stopping.",
        "text": "I noticed the front glass could use some attention, so I wanted to introduce myself. We help businesses keep the entrance looking clean without making it a big project. Who usually handles that here?",
    },
    {
        "category": "Door Knocking",
        "title": "Strip Mall / Plaza Approach",
        "use_case": "Talking to several businesses in the same plaza.",
        "text": "I'm working with a few businesses in this plaza today and wanted to stop in while I was nearby. Who would be the best person to talk with about keeping the storefront clean on a simple schedule?",
    },
    {
        "category": "Door Knocking",
        "title": "Can I Leave a Card?",
        "use_case": "When the right person is not available.",
        "text": "Can I leave a card for the owner or manager? If you know the best time to reach them, I will make a note so I do not keep catching you at the wrong time.",
    },
    {
        "category": "Door Knocking",
        "title": "Returning After Previous Stop",
        "use_case": "Coming back after a prior visit.",
        "text": "Hi, I stopped by recently and was told this might be a better time to catch the manager. Is now okay for a quick question about your service provider?",
    },
    {
        "category": "Cold Calling",
        "title": "First Cold Call",
        "use_case": "Calling a business before visiting.",
        "text": "Hi, this is [Name] with [Company]. We help local businesses with [Service]. I was calling to see who handles that for your location. Is that the manager, owner, or someone at corporate?",
    },
    {
        "category": "Cold Calling",
        "title": "Ask for Decision Maker",
        "use_case": "Finding the right person quickly.",
        "text": "Who would be the best person to ask about getting a quote or setting up service for this location?",
    },
    {
        "category": "Cold Calling",
        "title": "Manager Unavailable",
        "use_case": "Staff answers but the manager is out.",
        "text": "No worries. What day or time is usually best to reach them? I can call back then instead of interrupting you.",
    },
    {
        "category": "Cold Calling",
        "title": "No Answer / Voicemail",
        "use_case": "Leaving a short voicemail.",
        "text": "Hi, this is [Name] with [Company]. We help local businesses with [Service]. I was reaching out to see if you are happy with your current setup or if you would like a quick quote. You can call or text me back at [Phone]. Thanks.",
    },
    {
        "category": "Cold Calling",
        "title": "Calling Property Managers",
        "use_case": "Calling leasing offices or property managers.",
        "text": "Hi, this is [Name] with [Company]. We help local service businesses and commercial properties with [Service]. Who handles vendor quotes for your plazas or properties in the area?",
    },
    {
        "category": "Cold Calling",
        "title": "Calling Franchises / Corporate Locations",
        "use_case": "When a location may not choose vendors locally.",
        "text": "I know some locations handle vendors locally and some go through corporate. Do you know which one applies here, or who I should reach out to?",
    },
    {
        "category": "Follow-Up",
        "title": "Same-Day Follow-Up",
        "use_case": "Following up later the same day.",
        "text": "Hey, this is [Name] with [Company]. I stopped by earlier today and wanted to follow up while it was fresh. Would it be helpful if I sent over a simple quote?",
    },
    {
        "category": "Follow-Up",
        "title": "2-3 Day Follow-Up",
        "use_case": "Following up after a few days.",
        "text": "Hi, this is [Name] with [Company]. I reached out a couple days ago about [Service]. I just wanted to see if this is worth a quick quote or if I should check back another time.",
    },
    {
        "category": "Follow-Up",
        "title": "Follow-Up After Quote",
        "use_case": "Checking in after sending pricing.",
        "text": "Hi [Name], I wanted to check in on the quote I sent over. Any questions, or would you like me to adjust the scope or schedule to fit better?",
    },
    {
        "category": "Follow-Up",
        "title": "Follow-Up After Door Knock",
        "use_case": "Calling after visiting in person.",
        "text": "Hi, this is [Name] with [Company]. I stopped by recently and wanted to follow up with the right person about [Service] for your location.",
    },
    {
        "category": "Follow-Up",
        "title": "Follow-Up After Voicemail",
        "use_case": "Second attempt after voicemail.",
        "text": "Hi, this is [Name] with [Company]. I left a quick message recently and wanted to try once more. Is there someone I should speak with about [Service]?",
    },
    {
        "category": "Cold Email",
        "title": "Simple Intro Email",
        "use_case": "First email when an email address is available.",
        "text": "Subject: Quick service question for [Business Name]\n\nHi [Name],\n\nMy name is [Name] with [Company]. We help local businesses with [Service], and I wanted to see if [Business Name] would be open to a quick quote.\n\nWould it be okay if I sent over pricing or stopped by briefly this week?\n\nThanks,\n[Name]\n[Company]\n[Phone]",
    },
    {
        "category": "Cold Email",
        "title": "Follow-Up Email",
        "use_case": "Following up after a call or visit.",
        "text": "Subject: Following up\n\nHi [Name],\n\nI wanted to follow up from my recent call/visit about [Service] for [Business Name]. If it helps, I can send a simple quote for one-time or recurring service.\n\nThanks,\n[Name]\n[Phone]",
    },
    {
        "category": "Cold Email",
        "title": "Property Manager Email",
        "use_case": "Emailing a property manager.",
        "text": "Subject: Vendor quote for your properties\n\nHi [Name],\n\nMy name is [Name] with [Company]. We help commercial properties and local businesses with [Service]. Who would be the best person to contact about vendor quotes for your properties?\n\nThanks,\n[Name]\n[Company]\n[Phone]",
    },
    {
        "category": "Cold Email",
        "title": "Quick Quote?",
        "use_case": "Short email for busy owners.",
        "text": "Subject: Quick quote?\n\nHi [Name],\n\nWould you be open to a quick quote for [Service] at [Business Name]? I can keep it simple and send pricing without taking much of your time.\n\nThanks,\n[Name]",
    },
    {
        "category": "Cold Email",
        "title": "Seasonal Cleaning Email",
        "use_case": "Seasonal or periodic service reminder.",
        "text": "Subject: Seasonal service for [Business Name]\n\nHi [Name],\n\nWe are helping local businesses get ready for the season with [Service]. Would you like a quick quote for [Business Name] this week?\n\nThanks,\n[Name]\n[Phone]",
    },
    {
        "category": "Objections",
        "title": "We Already Have Someone",
        "use_case": "They already use another provider.",
        "text": "No problem. Are you happy with the quality and reliability? If anything changes, would it be okay if I left my card as a backup option?",
    },
    {
        "category": "Objections",
        "title": "Not Interested",
        "use_case": "They reject the pitch quickly.",
        "text": "I understand. I do not want to waste your time. Would it be okay if I left my information in case something changes later?",
    },
    {
        "category": "Objections",
        "title": "Too Expensive",
        "use_case": "They push back on price.",
        "text": "Totally understand. We can usually adjust the scope or frequency so it fits better. Would exterior-only or a less frequent schedule make more sense?",
    },
    {
        "category": "Objections",
        "title": "Send Information",
        "use_case": "They ask for details by email.",
        "text": "Absolutely. What is the best email to send it to, and who should I address it to? I will keep it short and include the basics.",
    },
    {
        "category": "Objections",
        "title": "Corporate Handles It",
        "use_case": "Local staff says vendors are corporate controlled.",
        "text": "That makes sense. Do you know if there is a facilities contact, vendor portal, or corporate email I should use?",
    },
    {
        "category": "Objections",
        "title": "Call Back Later",
        "use_case": "They are open but busy.",
        "text": "Sure. What day and time is usually best? I will make a note and call back then.",
    },
    {
        "category": "Objections",
        "title": "We Only Clean In-House",
        "use_case": "They handle the work themselves.",
        "text": "Got it. If you ever get too busy or need backup for a bigger cleanup, would it be okay if I left my information?",
    },
]
